/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirdkp;

/**
 *
 * @author USER
 */
public class TA extends javax.swing.JFrame {

    /**
     * Creates new form TA
     */
    public TA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apakah1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        apakah2 = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kolomHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Apakah kamu pacar ideal?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 550, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setLabelFor(apakah1);
        jLabel2.setText("Bila pacar kamu chatting dengan lawan jenisnya");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 88, 520, 30));

        apakah1.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        apakah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membunuhnya", "Menyelidikinya", "Biarin aja yang penting dia bahagia hehe" }));
        apakah1.setAutoscrolls(true);
        apakah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apakah1ActionPerformed(evt);
            }
        });
        getContentPane().add(apakah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 490, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setLabelFor(apakah2);
        jLabel3.setText("Bila pacar kamu capek dan butuh tidur dirumah sehingga tidak bisa pergi bersamamu denganmu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 610, 29));

        apakah2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membakar rumahnya", "Mencari tahu apakah dia benar capek atau main dengan selingkuhannya", "Menelponnya dan berkata \"Selamat tidur\"" }));
        apakah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apakah2ActionPerformed(evt);
            }
        });
        getContentPane().add(apakah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, 490, 30));

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHitung.setText("Cek");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 242, 100, 58));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jangan baper liat hasilnya ya");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 307, 320, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(kolomHasil);
        jLabel5.setText("HASIL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 341, 570, 49));

        kolomHasil.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kolomHasil.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(kolomHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 397, 420, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apakah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apakah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apakah1ActionPerformed

    private void apakah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apakah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apakah2ActionPerformed
public static int result (int persen, int persen2){
    int hasil = persen + persen2;
    return hasil;
}
    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed

int a = apakah1.getSelectedIndex();
int b = apakah2.getSelectedIndex();
int persen = 0;
int persen2 = 0;
int hasil  = 0;

switch(a){
case (0):
persen = 0;
break;
case (1) :
persen = 30;
break;
case (2) :
persen = 50;
break;
}
switch(b) {
    case (0):
    persen2 = 0;
    break;
    case (1):
    persen2 = 30;
    break;
    case (2):
    persen2 = 50;
    break;
}
       
hasil = result(persen,persen2);
kolomHasil.setText("Kamu "+hasil+"% pacar ideal");
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> apakah1;
    private javax.swing.JComboBox<String> apakah2;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kolomHasil;
    // End of variables declaration//GEN-END:variables
}
